### ISSUE TITLE
numpy not found

### ISSUE THREAD

**Issue by quantatanu** [brettviren/gegede#16]
Hi,

I am getting `ModuleNotFoundError: No module named 'numpy'`, when I try to `import numpy` in one of my `builder` code. 
`numpy` wasn't installed when I installed GeGeDe, but then I did install it outside the venv through `pip3 install numpy` successfully, but the error persists even after deactivating and re-activating the venv. Then I tried to install it inside the `venv` through `pip3 install numpy` and getting the following error:

`/my_ggd_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin/pip3: 2: exec: /root_path/root_builds/root_build-v6-24-06_python3/ggdvenv/bin/python3: not found` 

I don't understand that `root build path` though, ROOT was installed in a different directory called `root_install-v6-24-06_python3` but it was built from `root_build-v6-24-06_python3`, but ROOT is completely independent, why would it even show up here. 

Can you please help?

**Comment by brettviren** [comment]
Hi @quantatanu 

I guess this issue isn't related to gegede, per se.

In general, one needs to always create a Python environment in a fully consistent way.  Mixing/matching can sometimes be made to work but that relies on luck or being very careful/expert.

If you want to use `numpy` in your builder code, you certainly can, but you'll need to `pip install numpy` from a shell session that is currently "active" in the `venv` (or whatever environment management you may use).

In particular, you say you did the `pip3 install numpy` outside the `venv`. That would  put it where?  In `~/.local/`?  In any case, not somewhere connected with the `venv`.

Also, beware of setting `PATH` or `PYTHONPATH` or other similar variables by hand when using `venv`.  You should not need to and if you do, it will very likely cause problems like you describe.

**Comment by quantatanu** [comment]
Hi @brettviren

thanks for your reply. 

> If you want to use `numpy` in your builder code, you certainly can, but you'll need to `pip install numpy` from a shell session that is currently "active" in the `venv` (or whatever environment management you may use).
I got this error when I tried to `pip3 install numpy` from the active "ggdvenv" environment that I set up during GeGeDe installation following the [installation](https://github.com/brettviren/gegede/blob/master/doc/install.org) instruction. 

`/my_ggd_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin/pip3: 2: exec: /root_path/root_builds/root_build-v6-24-06_python3/ggdvenv/bin/python3: not found`

>In particular, you say you did the pip3 install numpy outside the venv. That would put it where? In ~/.local/? In any case, not somewhere connected with the venv.

It's in:  `~/.local/lib/python3.8/site-packages`


>beware of setting PATH or PYTHONPATH or other similar variables by hand when using venv. You should not need to and if you do, it will very likely cause problems like you describe.

I think I understand the `ROOT` cause, I followed every step of your `installation` instruction, and did:

`export PYTHONPATH=$HOME/opt/root/lib`
`export LD_LIBRARY_PATH=$HOME/opt/root/lib`

replacing the `$HOME/opt/root` by my `$ROOTSYS`. Shouldn't GeGeDe find `~/.local/lib/python3.8/site-packages` automatically? Or I should have to export the path?

**Comment by brettviren** [comment]
A venv is intended to isolate the environment.  Only what is installed
while in the environment should be what is available.

In particular, OS packages and things under `~/.local/` should
explicitly **not** leak in.  You can test that yourself.  Here's me
running Python from a fresh env which lacks a particular package I
have under `~/.local/` (`herbie`) and one installed at OS level
(`twisted`).

```
❯ python3 -m venv venv-junk

❯ source venv-junk/bin/activate.fish

❯ which python
/home/bv/venv-junk/bin/python

❯ python -c 'import sys; print("\n".join(sys.path))'

/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/bv/venv-junk/lib/python3.9/site-packages

❯ ls .local/lib/python3.9/site-packages/herbie/__init__.py
.local/lib/python3.9/site-packages/herbie/__init__.py

❯ python -c 'import herbie'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'herbie'

❯ python -c 'import twisted'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'twisted'


```

OTOH, in a fresh shell, outside the venv I can see both OS and `~/.local/`.

```
❯ python -c 'import sys; print("\n".join(sys.path))'

/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/bv/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.9/dist-packages

❯ dpkg -l|grep python|grep twisted
ii  python3-twisted                                  20.3.0-7                        all          Event-based framework for internet applications
ii  python3-twisted-bin:amd64                        20.3.0-7                        amd64        Event-based framework for internet applications

❯ which python
/usr/bin/python

❯ python -c 'import herbie; print(herbie.version)'
0.0.0

❯ /usr/bin/python -c 'import twisted; print (twisted.version)'
[Twisted, version 20.3.0]

```



This Python setup stuff can become really crazy if you mix-and-match.  My recomendation:

1. Use many, separate venvs, one for each project.
2. Try to keep each venv "pure" (do not make them with `--system-site-packages`).
3. Avoid setting Python environment variables.
4. Avoid ever doing `pip install --user`.  

Of course, there are exceptions.
Eg, adding the ROOT area to `PYTHONPATH` *should* be okay as long as PyROOT was built with the same Python.


I also recommend using use `direnv` to activate venvs when you `cd`
into some main work directory.  It helps to capture all setup and
helps you avoid having to remember details.  Once a directory setup
works, it keeps working with less things that can go wrong over time.

**Comment by quantatanu** [comment]
Hi @brettviren 

thank you for such a detailed reply, it was very helpful. I haven't learned python and have never used it before GeGeDe, in the past also I once used GeGeDe (about a year or so ago), that's why I was totally ignorant about all the virtual env stuff. Your answer is a good starting point for me.

At this moment, as GeGeDe is the only thing python that I am using, I am going to use it at an OS level and keep the venv aside for a while until I understand it better though using other minor example projects.

Thank you
