### ISSUE TITLE
NameError with python 3.13

### ISSUE THREAD

**Issue by diaza** [brettviren/gegede#24]
When I try running gegede with python 3.13, I would get a NameError. As an example, I try running one of the [GeGeDe Example](https://github.com/brettviren/gegede-example) scripts and paste the error below.  The error is resolved when I use python 3.12.

```
(gegedeenv) diaza@Alejandros-Laptop-2 gegede-example % gegede-cli -o ggdex.gdml ggdex.cfg
Traceback (most recent call last):
  File "/Users/diaza/anaconda3/envs/gegedeenv/bin/gegede-cli", line 33, in <module>
    sys.exit(load_entry_point('gegede==0.8', 'console_scripts', 'gegede-cli')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/diaza/anaconda3/envs/gegedeenv/lib/python3.13/site-packages/gegede-0.8-py3.13.egg/gegede/main.py", line 89, in main
    cfg = parse_config(args.config)
  File "/Users/diaza/anaconda3/envs/gegedeenv/lib/python3.13/site-packages/gegede-0.8-py3.13.egg/gegede/main.py", line 27, in parse_config
    cfg = gegede.configuration.configure(filenames)
  File "/Users/diaza/anaconda3/envs/gegedeenv/lib/python3.13/site-packages/gegede-0.8-py3.13.egg/gegede/configuration.py", line 116, in configure
    dat = evaluate(pod)
  File "/Users/diaza/anaconda3/envs/gegedeenv/lib/python3.13/site-packages/gegede-0.8-py3.13.egg/gegede/configuration.py", line 99, in evaluate
    newdat[k] = make_class(v)
                ~~~~~~~~~~^^^
  File "/Users/diaza/anaconda3/envs/gegedeenv/lib/python3.13/site-packages/gegede-0.8-py3.13.egg/gegede/configuration.py", line 83, in make_class
    return eval(fqclass)
  File "<string>", line 1, in <module>
NameError: name 'ggdex' is not defined
```

**Comment by brettviren** [comment]
Thanks @diaza 

I don't know what has changed in Python 3.13 but the way that modules were being resolved from strings was a little janky regardless.  That code was from before I learned about `importlib`. 

In case it is useful, I'll make a new release.
